name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npx cypress install
        
      - name: Run Unit Tests
        run: npm test -- --watch=false
        
      - name: Run E2E Tests
        run: |
          # Build production assets
          echo "Building production assets..."
          npm run build
          
          # Start production server in background
          echo "Starting production server..."
          npx vite preview --host 0.0.0.0 --port 5173 > server.log 2>&1 &
          
          # Wait for server to be ready
          echo "Waiting for server to start..."
          npx wait-on http://localhost:5173 --timeout 30000
          
          # Run Cypress tests with retry
          echo "Running E2E tests..."
          npx cypress run --browser chrome --headless || \
          (echo "First run failed, retrying after delay..." && \
           sleep 5 && \
           npx cypress run --browser chrome --headless)