name: Continuous Integration
 
on:
  pull_request:
    branches:
      - master
 
jobs:
  automation-test-job:
    runs-on: ubuntu-latest
    
    # Add environment variables for testing
    env:
      CI: true
      NODE_ENV: test
      CYPRESS_BASE_URL: http://localhost:5173
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          npm ci
          npx cypress install
        
      - name: Run tests
        run: |
          # Start the development server in the background
          nohup npm run dev > server.log 2>&1 &
          
          # Wait for the server to start
          npx wait-on http://localhost:5173
          
          # Run Cypress tests with retry
          npx cypress run --browser chrome --headless || \
          (echo "First run failed, retrying after delay..." && \
           sleep 5 && \
           npx cypress run --browser chrome --headless)