name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: |
          # Start development server in background
          npm run dev &
          
          # Wait for server to start
          npx wait-on http://localhost:5173
          
          # Run tests
          npm run test:e2e
          npm run ci:test